directories:
  output: release
  buildResources: public
appId: com.pokereport.launcher
productName: PokeReport Launcher
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - public/**/*
asar: false
extraMetadata:
  main: dist-electron/main.js
win:
  target: nsis
  publisherName: PokeReport Team
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  deleteAppDataOnUninstall: false
electronDownload:
  cache: ./cache
mac:
  target:
    - dmg
  icon: src/assets/icons/icon.icns
  category: public.app-category.games
linux:
  target:
    - AppImage
  icon: src/assets/icons/icon.png
  category: Game
electronVersion: 28.3.3
